### ISSUE TITLE
move eris/base to use Alpine+golang

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/common#32]
the base Jessie image is (a) too big; and (b) has security vulnerabilities.

let's move to a more controlled (less attack surface) and smaller base such as Alpine if we can. Because eris/base assumes that golang is installed we will need to have that usable (for now).

**Comment by ebuchman** [comment]
iirc, lots of alpine uses just copy in binaries rather than building in the image - is this something we should do as well?

**Comment by AFDudley** [comment]
The problem with doing this is Alpine is not supported on digital ocean. I don't want to hack support in, I rather just use a provider that lets us do normal things, like pick which OS we run.

**Comment by compleatang** [comment]
yeah container image `quay.io/eris/base`

agree with the former.

**Comment by AFDudley** [comment]
@ebuchman We can have build containers and prod containers.

**Comment by AFDudley** [comment]
Does the code that runs in the containers make any assumptions about the environment, like use bash?

**Comment by compleatang** [comment]
Will need to check the following images (somehow): https://github.com/search?q=%22FROM+quay.io%2Feris%2Fbase%22&type=Code&utf8=%E2%9C%93

eris-cli should run most of them. but others may need to be tested via their repository level test suites.

Also, we need to add the following to eris/base:

```
https://github.com/search?q=%22FROM+quay.io%2Feris%2Fbase%22&type=Code&utf8=%E2%9C%93

**Comment by zramsay** [comment]
almost done. @shuangjj has done most of the heavy lifting re-building all the images and testing them. I'm confirming it all works then we should be good to go.
