### ISSUE TITLE
Docker build and push should be separated for testing purposes

### ISSUE THREAD

**Issue by AFDudley** [eris-ltd/common#35]
https://github.com/eris-ltd/common/blob/master/docker/build.sh#L64
https://github.com/eris-ltd/common/blob/master/docker/build.sh#L82

Both assume that because we are building images we want to push them, this is not true in the context of testing.

**Comment by compleatang** [comment]
that file is currently used for our nightly builds (which do what they say on the tin, build and push). 

feel free to start separating those out, but the work needs to get coordinated with https://github.com/eris-ltd/eris-services/issues/22 and we'll need to get you access to the build machine for making sure that keeps building.

**Comment by AFDudley** [comment]
I think for testing it makes sense to just add a build_for_test script that copies the build.sh and omits the push part. we can then work to remove the other file later.

**Comment by AFDudley** [comment]
Templates have been created to have this process separated in jenkins.

**Comment by compleatang** [comment]
closing this issue as it's more cleanly covered in many issues in operations.
