### ISSUE TITLE
Use a shell command to determine the location of compilers in the scratch directory

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/common#38]
....I just spent....so many frustrating hours...wondering why the eris-compilers weren't working....and I finally found it. It's hidden in the scratch directory. Please....whenever this is initialized, run a shell command to determine its location before assuming the location of the compilers.

**Comment by VoR0220** [comment]
scratch that, just assume that the compilers are in the path...if they haven't got it in the path...IDEK.

**Comment by compleatang** [comment]
@VoR0220 am not sure this is actionable. Compiler binaries are added to the PATH via apt-get so that's handled. Closing for now, but if you can reframe this so it's actionable then we should reopen.
