### ISSUE TITLE
Container dependency clean up

### ISSUE THREAD

**Issue by AFDudley** [eris-ltd/common#55]
Currently,
bitcoinclassic
bitcoincore
geth
node
openbazaar-server
parity
zcash

are built from the tools container, which contains (a rather large) solc.
I think we want to:
put all the build tools into the build container
remove the tools container
put the ethereum stuff in it's own container
move built binaries into their own containers.

Are there any issues with this plan?

**Comment by AFDudley** [comment]
I have a static solc binary creator dockerfile, need to write jenkins jobs to build all of these.

**Comment by zramsay** [comment]
this has been completed. most third party images have moved to the `hello-eris` repo
