### ISSUE TITLE
Unable to pull eris files using eros 0.12.0 

### ISSUE THREAD

**Issue by mounik92** [eris-ltd/common#77]
When i try to initiate eris using eris init , it quits and shows error message as shown below . 
Tried cleaning complete eris working deirectory and got new docket - machine still the issue persists .
when trying to access eris images directly it downloads successfully . 

Any steps or changes to get this working

![capture](https://cloud.githubusercontent.com/assets/11531952/18240317/85e4bf08-7368-11e6-8f45-ad1f37790dda.PNG)

**Comment by zramsay** [comment]
Hi @mounik92 thank you for reporting this issue! The solution can be found in [this comment](https://github.com/eris-ltd/eris-cli/issues/761#issuecomment-227321949) then re-run the `eris init` command. Once all the images are on your host, `eris init` will be quick. We are working on adding a [manual override](https://github.com/eris-ltd/eris-cli/issues/896). If the problem persists, please open this issue in [eris-cli](https://github.com/eris-ltd/eris-cli/issues) or add comments in [this issue](https://github.com/eris-ltd/eris-cli/issues/761). Thanks again!

**Comment by mounik92** [comment]
Was not able to pull the images even after trying steps in complete thread , 
Its time out issue which ends at 5*time.minute , if this is configurable that would be good , 

Trying to change that part in source and trying to initialise using local build

**Comment by zramsay** [comment]
To be clear, `docker pull quay.io/eris/*`for each image timed-out after each image? Could you upload a screenshot?

**Comment by mounik92** [comment]
No docker pull quay.io/eris/* was successfull , but took time more than 5 minutes (specified in writer.go timeout) , editing the timeout value helped me to complete the initialize operation .

**Comment by pietv** [comment]
Yes, the default timeout has been increased to 15 minutes (for most, it takes less than 1m per image, so 5 minutes seemed a reasonable default). Thank you for the feedback and that you've been able rebuild the CLI with a new default. Right now the timeout variable change has been merged to the #develop branch.
